### PR TITLE
fix(cloudfront-function): treeshaking and exports are breaking function code

### LINKED ISSUE #1608: CloudFront Functions must export the `handler` function to work with the esbuild process, but `export` is not valid syntax in CloudFront Runtime
**Describe the bug**

In migrating some CloudFront functions from raw `.js` files to the new `esbuild` tool introduced with #1606, I was seeing empty CloudFront function code in my template:

```shell
Resources
[~] AWS::CloudFront::Function InstagramRedirectFunction InstagramRedirectFunctionAFBBF8C9
 ├─ [~] FunctionCode
 │   ├─ [-] function handler(event) {
  var response = {
    statusCode: 302,
    statusDescription: 'Found',
    headers: { location: { value: 'https://instagram.com/foobar' } },
  };
  return response;
}

 │   └─ [+]
```

(The code is blank on the diff)

Once I exported the handler in my file:

```diff
diff --git a/lib/InstagramRedirect.ts b//lib/InstagramRedirect.ts
index c2d276b..db8d695 100644
--- a/lib/InstagramRedirect.ts
+++ b/lib/InstagramRedirect.ts
@@ -1,4 +1,4 @@
-function handler(_: AWSCloudFrontFunction.Event): AWSCloudFrontFunction.Response {
+export function handler(_: AWSCloudFrontFunction.Event): AWSCloudFrontFunction.Response {
   const response: AWSCloudFrontFunction.Response = {
     statusCode: 302,
     statusDescription: 'Found',
```

Then, I saw the code being generated:

```shell
Resources
[~] AWS::CloudFront::Function InstagramRedirectFunction InstagramRedirectFunctionAFBBF8C9
 ├─ [~] FunctionCode
 │   ├─ [-] function handler(event) {
  var response = {
    statusCode: 302,
    statusDescription: 'Found',
    headers: { location: { value: 'https://instagram.com/foobar' } },
  };
  return response;
}

 │   └─ [+] function handler(_){return{statusCode:302,statusDescription:"Found",headers:{location:{value:"https://instagram.com/foobar"}}}}export{handler};
```

However, CloudFront doesn't like the `export` at the end of the generated code. It throws this error:

> The CloudFront function associated with the CloudFront distribution is invalid or could not run. SyntaxError: Illegal export statement in 1

If I remove the `export{handler}` from the end of the file:

```diff
1c1
< function handler(_){return{statusCode:302,statusDescription:\"Found\",headers:{location:{value:\"https://instagram.com/foobar\"}}}}export{handler};
---
> function handler(_){return{statusCode:302,statusDescription:\"Found\",headers:{location:{value:\"https://instagram.com/foobar\"}}}}
```

It works.

**To Reproduce**

Create a CloudFront TypeScript file such as:

```ts
function handler(_: AWSCloudFrontFunction.Event): AWSCloudFrontFunction.Response {
  const response: AWSCloudFrontFunction.Response = {
    statusCode: 302,
    statusDescription: 'Found',
    headers: { location: { value: 'https://instagram.com/foobar' } },
  };
  return response;
}
```

and import it as such:

```ts
const runtime = FunctionRuntime.JS_2_0;

functionAssociations: [
  {
    eventType: FunctionEventType.VIEWER_REQUEST,
    function: new Function(this, 'InstagramRedirectFunction', {
      code: CloudFrontTypeScriptCode.fromFile(join(__dirname, 'InstagramRedirect.ts'), {
        runtime,
      }),
      runtime,
    }),
  },
],
```

Without `handler` being `export`'ed, you'll see that the function code is empty. If you do export it, it produces this code:

```ts
function handler(_){return{statusCode:302,statusDescription:\"Found\",headers:{location:{value:\"https://instagram.com/foobar\"}}}}export{handler};
```

However, the `export{handler};` bit is illegal for the runtime.

**Expected behavior**

Two things:

## 1. Produce compatible code

If we can't have `export`s in the final code, we need to either tell `esbuild` to remove it, or
do some post-processing ourselves to remove it.

## 2. Warn if `export` is required

All of the AWS docs referenced by https://github.com/mrgrain/cdk-esbuild#amazon-cloudfront-functions (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/function-code-choose-purpose.html) just show defining `function handler`, not `export function handler`.

So it feels like the `export function` piece is an implementation detail specific to this use case / esbuild. It would be nice to throw an exception or warning to point people in this direction. Maybe it could be as simple as:

> If the code produced by esbuild is an empty string, say something like "`esbuild` produced an empty file. Did you remember to `export` a function named `handler` in <filepath>?"

**Versions:**
 - CDK: 2.212.0
 - Node.js: 22.x LTS

**Additional context**

### PR DESCRIPTION
**Pull request by blimmer**
Fixes #1608

### CODE REVIEW

File: src/cloudfront-function-code.ts [hunk 1]
```diff
@@ -245,3 +247,22 @@ function getSupportedFeatures(runtimeVersion: CloudFrontFunctionRuntime) {
     'async-await': isV2,
   };
 }
+
+/**
+ * Validates CloudFront Function code meets requirements.
+ * @throws Error if code contains export statements
+ */
+function validateCloudFrontFunctionCode(code: string): void {
```
Comment (blimmer) [inline src/cloudfront-function-code.ts:258]: We could also leave it to the user to find out that `export` statements don't work. I, personally, like warning at compile time vs. waiting for the deployment to fail.

However, if we're concerned that this regex is too brittle, I could see removing it (or using a warning vs. an Error).

**Review by mrgrain — APPROVED** [review]

**Comment by mrgrain** [comment]
@mergifyio requeue

**Comment by mrgrain** [comment]
@mergifyio queue

**Review by mrgrain — APPROVED** [review]
